# Generated by Django 5.1.6 on 2025-02-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataProName', models.CharField(max_length=200)),
                ('DataProDescription', models.CharField(max_length=600)),
                ('DataProTools', models.CharField(max_length=200)),
            ],
        ),
    ]
