# Generated by Django 4.2.19 on 2025-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tools', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataProfession',
        ),
    ]
