# Generated by Django 4.2.19 on 2025-03-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0004_category_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacareer',
            name='content',
        ),
    ]
