# Generated by Django 4.2.19 on 2025-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0006_datacareer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacareer',
            name='content',
        ),
        migrations.AddField(
            model_name='datacareer',
            name='main_task',
            field=models.JSONField(default=list),
        ),
    ]
