# Generated by Django 4.2.19 on 2025-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0007_remove_datacareer_content_datacareer_main_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GloosaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
    ]
