# Generated by Django 4.2.19 on 2025-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0008_gloosaryterm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GloosaryTerm',
            new_name='GlossaryTerm',
        ),
    ]
