# Generated by Django 4.2.19 on 2025-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0011_alter_article_content_alter_article_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
