# Generated by Django 4.2.19 on 2025-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapro', '0013_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
